before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/deepclean
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: mac
      amd64: x64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - tap:
      owner: mroth
      name: homebrew-formulas
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Scan and remove junk files from source code directories"
    homepage: "https://github.com/mroth/deepclean"
    skip_upload: false
changelog:
  skip: true
